"""add billing tables

Revision ID: e609308705ad
Revises: 1d22c3a230c1
Create Date: 2026-04-19 10:00:03.222740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e609308705ad'
down_revision: Union[str, None] = '1d22c3a230c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('subscription', 'infra', 'tool', 'service', 'other', name='billing_category'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('cycle', sa.Enum('monthly', 'yearly', 'one_time', name='billing_cycle'), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_category'), 'billings', ['category'], unique=False)
    op.create_table('billing_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('billing_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_payments_billing_id'), 'billing_payments', ['billing_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_paid_date'), 'billing_payments', ['paid_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_payments_paid_date'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_billing_id'), table_name='billing_payments')
    op.drop_table('billing_payments')
    op.drop_index(op.f('ix_billings_category'), table_name='billings')
    op.drop_table('billings')
    # ### end Alembic commands ###
